# Generated by Django 4.0.4 on 2022-06-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itnext', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Happy Customers', 'Happy Customers'), ('Repaired Laptops', 'Repaired Laptops'), ('Repaired Computers', 'Repaired Computers'), ('OS INSTALLED', 'OS INSTALLED')], max_length=100)),
                ('quantity', models.IntegerField(blank=True)),
                ('logo', models.FileField(upload_to='logo/')),
            ],
        ),
    ]
