# Generated by Django 4.0.4 on 2022-06-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itnext', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
    ]
