# Generated by Django 4.0.4 on 2022-06-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itnext', '0003_service_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='password',
        ),
    ]
